-- H2 测试 Schema（MySQL 兼容模式）
-- 仅包含测试需要的表，不包含存储过程/触发器/GET_LOCK 等 MySQL 特有语法

CREATE TABLE IF NOT EXISTS admin (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(30) DEFAULT 'ADMIN',
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS member (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  gender TINYINT DEFAULT 0,
  level INT DEFAULT 0,
  points INT DEFAULT 0,
  balance DECIMAL(10,2) DEFAULT 0.00,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  tags VARCHAR(255) DEFAULT NULL,
  birthday DATE DEFAULT NULL,
  birthday_type TINYINT DEFAULT 0,
  last_consume_date DATE DEFAULT NULL,
  last_visit_date DATE DEFAULT NULL,
  total_spent DECIMAL(10,2) DEFAULT 0.00,
  visit_count INT DEFAULT 0,
  rfm_segment VARCHAR(20) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  openid VARCHAR(64) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS recharge_record (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  pay_method TINYINT DEFAULT 1,
  remark VARCHAR(255) DEFAULT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_item (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  category_id BIGINT DEFAULT NULL,
  price DECIMAL(10,2) NOT NULL,
  duration INT DEFAULT 60,
  description VARCHAR(500) DEFAULT NULL,
  status TINYINT DEFAULT 1,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS consumption_order (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  pay_method TINYINT DEFAULT 1,
  pay_amount DECIMAL(10,2) DEFAULT 0.00,
  balance_used DECIMAL(10,2) DEFAULT 0.00,
  points_earned INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  pay_remark VARCHAR(255) DEFAULT NULL,
  coupon_id BIGINT DEFAULT NULL,
  coupon_discount DECIMAL(10,2) DEFAULT 0.00,
  employee_id BIGINT DEFAULT NULL,
  commission_amount DECIMAL(10,2) DEFAULT 0.00,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS consumption_order_item (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  item_id BIGINT NOT NULL,
  item_name VARCHAR(100) DEFAULT NULL,
  item_price DECIMAL(10,2) NOT NULL,
  quantity INT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS coupon (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  template_id BIGINT DEFAULT NULL,
  member_id BIGINT NOT NULL,
  coupon_name VARCHAR(100) DEFAULT NULL,
  discount_value DECIMAL(10,2) DEFAULT 0.00,
  condition_amount DECIMAL(10,2) DEFAULT 0.00,
  status TINYINT DEFAULT 1,
  expire_time TIMESTAMP DEFAULT NULL,
  receive_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  use_time TIMESTAMP DEFAULT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_card (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT NOT NULL,
  service_item_id BIGINT NOT NULL,
  total_count INT NOT NULL DEFAULT 0,
  used_count INT DEFAULT 0,
  price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  expire_date DATE DEFAULT NULL,
  status TINYINT DEFAULT 1,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customer_session (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT NOT NULL,
  token VARCHAR(64) NOT NULL,
  login_method VARCHAR(20) DEFAULT 'SMS_CODE',
  expire_at TIMESTAMP NOT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_buy_template (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  image_url VARCHAR(500) DEFAULT NULL,
  description VARCHAR(1000) DEFAULT NULL,
  original_price DECIMAL(10,2) NOT NULL,
  group_price DECIMAL(10,2) NOT NULL,
  group_size INT NOT NULL DEFAULT 2,
  expire_hours INT NOT NULL DEFAULT 24,
  start_time TIMESTAMP DEFAULT NULL,
  end_time TIMESTAMP DEFAULT NULL,
  total_qty INT DEFAULT 0,
  issued_qty INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  sort_order INT DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_buy_order (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  template_id BIGINT NOT NULL,
  order_no VARCHAR(32) NOT NULL,
  leader_id BIGINT NOT NULL,
  leader_name VARCHAR(50) DEFAULT NULL,
  leader_phone VARCHAR(20) DEFAULT NULL,
  group_price DECIMAL(10,2) NOT NULL,
  original_price DECIMAL(10,2) NOT NULL,
  group_size INT NOT NULL,
  current_size INT NOT NULL DEFAULT 1,
  expire_time TIMESTAMP NOT NULL,
  status TINYINT DEFAULT 1,
  complete_time TIMESTAMP DEFAULT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_buy_participant (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  member_id BIGINT NOT NULL,
  member_name VARCHAR(50) DEFAULT NULL,
  member_phone VARCHAR(20) DEFAULT NULL,
  join_price DECIMAL(10,2) NOT NULL,
  status TINYINT DEFAULT 1,
  is_leader TINYINT DEFAULT 0,
  join_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  complete_time TIMESTAMP DEFAULT NULL,
  refund_time TIMESTAMP DEFAULT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_detail (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  pay_method TINYINT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  transaction_id VARCHAR(64) DEFAULT NULL,
  pay_channel VARCHAR(20) DEFAULT NULL,
  qr_code_url VARCHAR(500) DEFAULT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notification_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT DEFAULT NULL,
  phone VARCHAR(20) NOT NULL,
  type VARCHAR(30) NOT NULL,
  template_code VARCHAR(50) DEFAULT NULL,
  content VARCHAR(500) DEFAULT NULL,
  status TINYINT DEFAULT 0,
  error_msg VARCHAR(255) DEFAULT NULL,
  sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_read TINYINT DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS appointment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT NOT NULL,
  service_item_id BIGINT DEFAULT NULL,
  employee_id BIGINT DEFAULT NULL,
  appointment_date DATE NOT NULL,
  start_time TIME DEFAULT NULL,
  end_time TIME DEFAULT NULL,
  duration INT DEFAULT NULL,
  status TINYINT DEFAULT 1,
  reminded TINYINT DEFAULT 0,
  remark VARCHAR(255) DEFAULT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
